#!/usr/bin/env python3

from collections import Counter

pcv2_rep_seq = 'SPSKKNGRSGPQPHKRWVFTLNNPSEDERKKIRDLPISLFDYFIVGEEGNEEGRTPHLQGFANFVKKQTFNKVKWYLGARCHIEKAKGTDQQNKEYCSKEGNLLMECGAPRSQGQR'

c = Counter(pcv2_rep_seq)
debug(c)
