#!/usr/bin/env python3

import regex

seq = 'gaagatcatcttattaatcagataaaatatttctagatttcagtgcaatttatctcttcaaatgtagcacctgaagtcagccccatacgatataagttgtaattctcatgtttgacagcttatcatcgataagctggacgtctaagaaaccattattatcatgacattaacctataaaaataggcgtatcacgaggccctttggataaccagaagcaataaaaaatcaaatcggatttcactatataatctcactttatctaagatgaatccgatggaagcatcctgttttctctcaatttttttatctaaaacccagcgttcgatgcttctttgagcgaacgatcaaaaataagtgccttcccatcaaaaaaatattgacaacataaaaaactttgtgttatacttgtaacgctacatggagattaactcaatctagctagagaggctttacactttatgcttccggctcgtataatgtgtggaattgtgagcggataacaatttcacacaggaaacagctatgaccatgattacggattcactggaactctagaccaaagagaggacaca'

pat = r'(ttgaca){s<=3}(.{15,19})(tataat){s<=3}'

promoters = regex.findall(pat, seq)

debug(promoters)

