#!/usr/bin/env bash
set -euo pipefail

klab_mutagenesis \
  ZIF_BSA \
  GATGAACGTAAACGTCATACCAAAAttcatctgcgtcagaaagatTGACTAGCATAACCCCTCTCTAAACGGAGGGGTTTaaaaggccaggaaccgtaaaaaggccgcgttgctggcgtt \
  GATGAACGTAAACGTCATACCAAAAttcatctgcgtcagaaagatAGAGACCTACAAGACGCGGTCTCAGGCTCAAGGGCGGGGGGCGGCGGGGAAAAGCTTCaaaaggccaggaaccgtaaaaaggccgcgttgctggcgtt \

klab_mutagenesis \
  BSA \
  taatacgactcactatagggcttaagtataaggaggaaaaaaTatggaacgtccgtatgcGTGTCCGGTGGAAAGCTGCGATCGTCGTTTTAGCCGTTCTGATGAACTGACCCGTCATATTCGTATTCATACCGGCCAGAAACCGTTTCAGTGCCGTATTTGCATGCGTAACTTTAGCCGTAGCGATCATCTGACCACCCATATTCGTACCCATACCGGCGAAAAACCGTTTGCGTGCGATATTTGCGGCCGTAAATTTGCGCGTTCTGATGAACGTAAACGTCATACCAAAAttcatctgcgtcagaaagatTGACTAGCATAACCCCTCTCTAAACGGAGGGGTTTaaaaggccaggaaccgtaaaaaggccgcgttgctggcgtt \
  taatacgactcactatagggcttaagtataaggaggaaaaaatatgagagacctacaagacgcggtctcaGGCTCAAGGGCGGGGGGCGGCGGGGAAAAGCTTCaaaaggccaggaaccgtaaaaaggccgcgttgctggcgtt \
