#!/usr/bin/env bash
set -euo pipefail

klab_mutagenesis \
  BSA \
  GTCAACAGTATAGAACCGTGGATGATGTGGTCTCTACAGGATCTGACATTATTATTGTTGG \
  GTCAACAGTATAGAACCGTGGATGATGTAGTCTCTACAGGATCTGACATTATTATTGTTGG

klab_mutagenesis \
  BBS1 \
  TACACATAGACGACCATCACACCACTGAAGACTGCGGGATTGCTCTCGGTCAAGCTTTTAA \
  TACACATAGACGACCATCACACCACTGAGGACTGCGGGATTGCTCTCGGTCAAGCTTTTAA

klab_mutagenesis \
  BBS2 \
  TATCCGCCAAGTACAATTTTTTACTCTTCGAAGACAGAAAATTTGCTGACATTGGTAATAC \
  TATCCGCCAAGTACAATTTTTTACTCTTCGAGGACAGAAAATTTGCTGACATTGGTAATAC

