[row]
C.replicate = 1
D.replicate = 2
E.replicate = 3

[col]
3.control = 'no-rt'
3.template_conc = 1e2
4.template_conc = 1e2
5.template_conc = 1e1
6.template_conc = 1e0
7.template_conc = 1e-1
8.template_conc = 1e-2
9.template_conc = 1e-3
10.control = 'no-template'
10.template_conc = 0
