[row]
C.replicate = 1
D.replicate = 2
E.replicate = 3

[col]
2.rnase_U_mL  = 1.000000e+02
3.rnase_U_mL  = 3.162278e+01
4.rnase_U_mL  = 1.000000e+01
5.rnase_U_mL  = 3.162278e+00
6.rnase_U_mL  = 1.000000e+00
7.rnase_U_mL  = 3.162278e-01
8.rnase_U_mL  = 1.000000e-01
9.rnase_U_mL  = 0

10.control = 'no-rt'
10.rnase_U_mL = 0
11.control = 'no-template'
11.rnase_U_mL = 0
